version: '3.8'

services:
  hrms-app:
    build: .
    ports:
      - "8000:8000"  # FastAPI/NiceGUI
      - "50051:50051"  # gRPC
    environment:
      - DATABASE_URL=postgresql://hrms_user:hrms_password@postgres:5432/hrms_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
      - /app/__pycache__
    networks:
      - hrms-network
    restart: unless-stopped

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: hrms_db
      POSTGRES_USER: hrms_user
      POSTGRES_PASSWORD: hrms_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/hrms_schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    networks:
      - hrms-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hrms-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - hrms-app
    networks:
      - hrms-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  hrms-network:
    driver: bridge