coverage_analysis:
  friday:
    required: 10
    scheduled: 8
    status: understaffed
  monday:
    required: 10
    scheduled: 8
    status: understaffed
  saturday:
    required: 6
    scheduled: 5
    status: adequate
  sunday:
    required: 4
    scheduled: 3
    status: adequate
  thursday:
    required: 10
    scheduled: 10
    status: optimal
  tuesday:
    required: 10
    scheduled: 10
    status: optimal
  wednesday:
    required: 10
    scheduled: 9
    status: adequate
schedule_requests:
- current_shift: morning
  employee_id: EMP001
  employee_name: John Smith
  id: REQ001
  priority: medium
  reason: Doctor appointment in the morning
  request_type: shift_change
  requested_date: '2025-10-15'
  requested_shift: afternoon
  status: pending
  submitted_date: '2025-10-10'
- employee_id: EMP002
  employee_name: Sarah Johnson
  id: REQ002
  priority: high
  reason: Personal appointment
  request_type: time_off
  requested_date: '2025-10-18'
  status: approved
  submitted_date: '2025-10-08'
schedule_settings:
  auto_optimization: true
  default_shift_duration: 8
  efficiency_weight: 0.3
  fairness_weight: 0.7
  max_hours_per_week: 40
  min_rest_hours: 12
  overtime_threshold: 8
  shift_change_notice_hours: 24
  week_start_day: monday
shift_templates:
  afternoon:
    break_duration: 60
    color: '#F59E0B'
    duration: 8
    end_time: '21:00'
    name: Afternoon Shift
    start_time: '13:00'
  evening:
    break_duration: 60
    color: '#8B5CF6'
    duration: 8
    end_time: 01:00
    name: Evening Shift
    start_time: '17:00'
  morning:
    break_duration: 60
    color: '#3B82F6'
    duration: 8
    end_time: '17:00'
    name: Morning Shift
    start_time: 09:00
  night:
    break_duration: 60
    color: '#1F2937'
    duration: 8
    end_time: 07:00
    name: Night Shift
    start_time: '23:00'
weekly_schedule:
  assignments:
    EMP001:
      department: IT
      friday:
        shift: morning
        status: scheduled
      monday:
        shift: morning
        status: scheduled
      name: John Smith
      saturday:
        shift: 'off'
        status: 'off'
      sunday:
        shift: 'off'
        status: 'off'
      thursday:
        shift: morning
        status: scheduled
      tuesday:
        shift: morning
        status: scheduled
      wednesday:
        shift: morning
        status: scheduled
    EMP002:
      department: HR
      friday:
        shift: afternoon
        status: scheduled
      monday:
        shift: afternoon
        status: scheduled
      name: Sarah Johnson
      saturday:
        shift: 'off'
        status: 'off'
      sunday:
        shift: 'off'
        status: 'off'
      thursday:
        shift: afternoon
        status: scheduled
      tuesday:
        shift: afternoon
        status: scheduled
      wednesday:
        shift: afternoon
        status: scheduled
    EMP003:
      department: Finance
      friday:
        shift: morning
        status: scheduled
      monday:
        shift: morning
        status: scheduled
      name: Mike Davis
      saturday:
        shift: morning
        status: scheduled
      sunday:
        shift: 'off'
        status: 'off'
      thursday:
        shift: morning
        status: scheduled
      tuesday:
        shift: morning
        status: scheduled
      wednesday:
        shift: 'off'
        status: 'off'
  week_of: '2025-10-13'
