MTS_20251118_EMP001001:
  ai_insights: []
  anomaly_detected: false
  approved_at: null
  approved_by: null
  break_duration: 50.0
  clock_in: 09:30
  clock_out: '17:15'
  date: '2025-11-18'
  employee_id: EMP001001
  entry_id: MTS_20251118_EMP001001
  hourly_rate: 28.5
  last_modified_at: '2025-12-01T15:57:52.931873'
  last_modified_by: AI_SYSTEM
  lunch_duration: 0
  meeting_hours: 1.343732831896745
  notes: ''
  overtime_hours: 0
  overtime_pay: 0.0
  productivity_score: 0.8
  regular_hours: 7.0
  regular_pay: 199.5
  remote_allowance: 0.0
  remote_hours: 0.0
  status: approved
  total_hours: 7.0
  total_pay: 199.5
MTS_20251119_EMP001001:
  ai_insights: []
  anomaly_detected: false
  approved_at: null
  approved_by: null
  break_duration: 70.0
  clock_in: 08:00
  clock_out: '18:00'
  date: '2025-11-19'
  employee_id: EMP001001
  entry_id: MTS_20251119_EMP001001
  hourly_rate: 28.5
  last_modified_at: '2025-12-01T15:57:52.931873'
  last_modified_by: AI_SYSTEM
  lunch_duration: 0
  meeting_hours: 2.5914254253174445
  notes: ''
  overtime_hours: 0.75
  overtime_pay: 32.06
  productivity_score: 0.8
  regular_hours: 8.0
  regular_pay: 228.0
  remote_allowance: 0.0
  remote_hours: 0.0
  status: approved
  total_hours: 8.75
  total_pay: 260.06
MTS_20251120_EMP001001:
  ai_insights: []
  anomaly_detected: false
  approved_at: null
  approved_by: null
  break_duration: 45.0
  clock_in: 08:15
  clock_out: '16:00'
  date: '2025-11-20'
  employee_id: EMP001001
  entry_id: MTS_20251120_EMP001001
  hourly_rate: 28.5
  last_modified_at: '2025-12-01T15:57:52.931873'
  last_modified_by: AI_SYSTEM
  lunch_duration: 0
  meeting_hours: 2.890117910515556
  notes: ''
  overtime_hours: 0
  overtime_pay: 0.0
  productivity_score: 0.8
  regular_hours: 7.0
  regular_pay: 199.5
  remote_allowance: 0.0
  remote_hours: 0.0
  status: approved
  total_hours: 7.0
  total_pay: 199.5
MTS_20251121_EMP001001:
  ai_insights: []
  anomaly_detected: false
  approved_at: null
  approved_by: null
  break_duration: 60.0
  clock_in: 08:00
  clock_out: '17:15'
  date: '2025-11-21'
  employee_id: EMP001001
  entry_id: MTS_20251121_EMP001001
  hourly_rate: 28.5
  last_modified_at: '2025-12-01T15:57:52.931873'
  last_modified_by: AI_SYSTEM
  lunch_duration: 0
  meeting_hours: 1.8685396232669247
  notes: ''
  overtime_hours: 0.25
  overtime_pay: 10.69
  productivity_score: 0.8
  regular_hours: 8.0
  regular_pay: 228.0
  remote_allowance: 0.0
  remote_hours: 0.0
  status: approved
  total_hours: 8.25
  total_pay: 238.69
MTS_20251124_EMP001001:
  ai_insights: []
  anomaly_detected: false
  approved_at: null
  approved_by: null
  break_duration: 55.0
  clock_in: 08:00
  clock_out: '16:30'
  date: '2025-11-24'
  employee_id: EMP001001
  entry_id: MTS_20251124_EMP001001
  hourly_rate: 28.5
  last_modified_at: '2025-12-01T15:57:52.931873'
  last_modified_by: AI_SYSTEM
  lunch_duration: 0
  meeting_hours: 1.5946648771231748
  notes: ''
  overtime_hours: 0
  overtime_pay: 0.0
  productivity_score: 0.8
  regular_hours: 7.5
  regular_pay: 213.75
  remote_allowance: 0.0
  remote_hours: 0.0
  status: approved
  total_hours: 7.5
  total_pay: 213.75
MTS_20251125_EMP001001:
  ai_insights: []
  anomaly_detected: false
  approved_at: null
  approved_by: null
  break_duration: 60.0
  clock_in: 08:30
  clock_out: '18:15'
  date: '2025-11-25'
  employee_id: EMP001001
  entry_id: MTS_20251125_EMP001001
  hourly_rate: 28.5
  last_modified_at: '2025-12-01T15:57:52.931873'
  last_modified_by: AI_SYSTEM
  lunch_duration: 0
  meeting_hours: 1.0204135277851574
  notes: ''
  overtime_hours: 0.75
  overtime_pay: 32.06
  productivity_score: 0.8
  regular_hours: 8.0
  regular_pay: 228.0
  remote_allowance: 0.0
  remote_hours: 0.0
  status: approved
  total_hours: 8.75
  total_pay: 260.06
MTS_20251126_EMP001001:
  ai_insights: []
  anomaly_detected: false
  approved_at: null
  approved_by: null
  break_duration: 75.0
  clock_in: 08:30
  clock_out: '16:15'
  date: '2025-11-26'
  employee_id: EMP001001
  entry_id: MTS_20251126_EMP001001
  hourly_rate: 28.5
  last_modified_at: '2025-12-01T15:57:52.931873'
  last_modified_by: AI_SYSTEM
  lunch_duration: 0
  meeting_hours: 0.505292009833038
  notes: ''
  overtime_hours: 0
  overtime_pay: 0.0
  productivity_score: 0.8
  regular_hours: 6.5
  regular_pay: 185.25
  remote_allowance: 25.0
  remote_hours: 6.5
  status: approved
  total_hours: 6.5
  total_pay: 210.25
MTS_20251127_EMP001001:
  ai_insights: []
  anomaly_detected: false
  approved_at: null
  approved_by: null
  break_duration: 75.0
  clock_in: 08:30
  clock_out: '18:15'
  date: '2025-11-27'
  employee_id: EMP001001
  entry_id: MTS_20251127_EMP001001
  hourly_rate: 28.5
  last_modified_at: '2025-12-01T15:57:52.931873'
  last_modified_by: AI_SYSTEM
  lunch_duration: 0
  meeting_hours: 1.5351732129903786
  notes: ''
  overtime_hours: 0.5
  overtime_pay: 21.38
  productivity_score: 0.8
  regular_hours: 8.0
  regular_pay: 228.0
  remote_allowance: 0.0
  remote_hours: 0.0
  status: approved
  total_hours: 8.5
  total_pay: 249.38
MTS_20251128_EMP001001:
  ai_insights: []
  anomaly_detected: false
  approved_at: null
  approved_by: null
  break_duration: 75.0
  clock_in: 08:30
  clock_out: '18:00'
  date: '2025-11-28'
  employee_id: EMP001001
  entry_id: MTS_20251128_EMP001001
  hourly_rate: 28.5
  last_modified_at: '2025-12-01T15:57:52.931873'
  last_modified_by: AI_SYSTEM
  lunch_duration: 0
  meeting_hours: 2.718354560574998
  notes: ''
  overtime_hours: 0.25
  overtime_pay: 10.69
  productivity_score: 0.8
  regular_hours: 8.0
  regular_pay: 228.0
  remote_allowance: 0.0
  remote_hours: 0.0
  status: approved
  total_hours: 8.25
  total_pay: 238.69
MTS_20251201_EMP001001:
  ai_insights: []
  anomaly_detected: false
  approved_at: null
  approved_by: null
  break_duration: 40.0
  clock_in: 08:30
  clock_out: '16:15'
  date: '2025-12-01'
  employee_id: EMP001001
  entry_id: MTS_20251201_EMP001001
  hourly_rate: 28.5
  last_modified_at: '2025-12-01T15:57:52.931873'
  last_modified_by: AI_SYSTEM
  lunch_duration: 0
  meeting_hours: 2.0741340093420213
  notes: ''
  overtime_hours: 0
  overtime_pay: 0.0
  productivity_score: 0.8
  regular_hours: 7.0
  regular_pay: 199.5
  remote_allowance: 25.0
  remote_hours: 7.0
  status: approved
  total_hours: 7.0
  total_pay: 224.5
