# Staff Data
# Contains employee information, real-time status, and department data

employees:
  EMP001:
    name: "John Smith"
    employee_id: "EMP001"
    department: "Engineering"
    position: "Senior Developer"
    email: "john.smith@company.com"
    phone: "+1-555-0101"
    shift: "morning"
    location: "Office Floor 3"
    current_status: "on_duty"
    last_status_update: "2025-10-12 14:30:00"
    check_in_time: "09:15"
    expected_check_out: "17:00"
    break_start: null
    total_hours_today: 5.25
    profile_image: null
    emergency_contact:
      name: "Jane Smith"
      phone: "+1-555-0201"
      relationship: "Spouse"
    hire_date: "2023-01-15"
    employee_type: "full_time"
    
  EMP002:
    name: "Sarah Johnson"
    employee_id: "EMP002"
    department: "Human Resources"
    position: "HR Manager"
    email: "sarah.johnson@company.com"
    phone: "+1-555-0102"
    shift: "morning"
    location: "Office Floor 2"
    current_status: "on_break"
    last_status_update: "2025-10-12 14:15:00"
    check_in_time: "08:45"
    expected_check_out: "17:00"
    break_start: "14:15"
    total_hours_today: 5.5
    profile_image: null
    emergency_contact:
      name: "Mike Johnson"
      phone: "+1-555-0202"
      relationship: "Spouse"
    hire_date: "2022-03-20"
    employee_type: "full_time"
    
  EMP003:
    name: "Mike Davis"
    employee_id: "EMP003"
    department: "Sales"
    position: "Sales Representative"
    email: "mike.davis@company.com"
    phone: "+1-555-0103"
    shift: "morning"
    location: "Remote - Home Office"
    current_status: "remote_work"
    last_status_update: "2025-10-12 14:30:00"
    check_in_time: "09:00"
    expected_check_out: "17:00"
    break_start: null
    total_hours_today: 5.5
    profile_image: null
    emergency_contact:
      name: "Lisa Davis"
      phone: "+1-555-0203"
      relationship: "Sister"
    hire_date: "2023-07-10"
    employee_type: "full_time"
    
  EMP004:
    name: "Lisa Wilson"
    employee_id: "EMP004"
    department: "Finance"
    position: "Financial Analyst"
    email: "lisa.wilson@company.com"
    phone: "+1-555-0104"
    shift: "morning"
    location: "Office Floor 1"
    current_status: "on_leave"
    last_status_update: "2025-10-11 17:00:00"
    check_in_time: null
    expected_check_out: null
    break_start: null
    total_hours_today: 0
    profile_image: null
    emergency_contact:
      name: "Tom Wilson"
      phone: "+1-555-0204"
      relationship: "Father"
    hire_date: "2022-11-05"
    employee_type: "full_time"
    
  EMP005:
    name: "David Brown"
    employee_id: "EMP005"
    department: "Engineering"
    position: "Junior Developer"
    email: "david.brown@company.com"
    phone: "+1-555-0105"
    shift: "morning"
    location: "Office Floor 3"
    current_status: "on_duty"
    last_status_update: "2025-10-12 09:30:00"
    check_in_time: "09:30"
    expected_check_out: "17:30"
    break_start: null
    total_hours_today: 5.0
    profile_image: null
    emergency_contact:
      name: "Mary Brown"
      phone: "+1-555-0205"
      relationship: "Mother"
    hire_date: "2024-02-01"
    employee_type: "full_time"
    
  EMP006:
    name: "Emily Chen"
    employee_id: "EMP006"
    department: "Marketing"
    position: "Marketing Specialist"
    email: "emily.chen@company.com"
    phone: "+1-555-0106"
    shift: "morning"
    location: "Office Floor 2"
    current_status: "on_duty"
    last_status_update: "2025-10-12 08:45:00"
    check_in_time: "08:45"
    expected_check_out: "16:45"
    break_start: null
    total_hours_today: 5.75
    profile_image: null
    emergency_contact:
      name: "James Chen"
      phone: "+1-555-0206"
      relationship: "Spouse"
    hire_date: "2023-05-15"
    employee_type: "full_time"

departments:
  Engineering:
    name: "Engineering"
    manager: "John Smith"
    total_staff: 15
    on_duty: 12
    on_break: 2
    off_duty: 1
    remote_work: 0
    on_leave: 0
    location: "Floor 3"
    budget_code: "ENG001"
    
  "Human Resources":
    name: "Human Resources"
    manager: "Sarah Johnson"
    total_staff: 5
    on_duty: 3
    on_break: 1
    off_duty: 1
    remote_work: 0
    on_leave: 0
    location: "Floor 2"
    budget_code: "HR001"
    
  Sales:
    name: "Sales"
    manager: "Mike Davis"
    total_staff: 10
    on_duty: 7
    on_break: 1
    off_duty: 0
    remote_work: 2
    on_leave: 0
    location: "Floor 1"
    budget_code: "SAL001"
    
  Finance:
    name: "Finance"
    manager: "Robert Taylor"
    total_staff: 8
    on_duty: 6
    on_break: 0
    off_duty: 1
    remote_work: 0
    on_leave: 1
    location: "Floor 1"
    budget_code: "FIN001"
    
  Marketing:
    name: "Marketing"
    manager: "Emily Chen"
    total_staff: 6
    on_duty: 5
    on_break: 1
    off_duty: 0
    remote_work: 0
    on_leave: 0
    location: "Floor 2"
    budget_code: "MKT001"

real_time_stats:
  total_employees: 44
  currently_on_duty: 33
  on_break: 5
  remote_workers: 2
  on_leave: 1
  off_duty: 3
  last_updated: "2025-10-12 14:30:00"
  
attendance_summary:
  today:
    present: 41
    absent: 3
    late_arrivals: 5
    early_departures: 2
    total_hours_worked: 287.5
    average_hours_per_employee: 7.01
    
  this_week:
    total_days: 5
    average_attendance_rate: 94.5
    total_overtime_hours: 42.5
    total_break_time_hours: 18.75
    
  this_month:
    working_days: 22
    average_attendance_rate: 93.2
    total_overtime_hours: 156.25
    sick_leave_taken: 24
    vacation_days_taken: 18

shift_assignments:
  morning_shift:
    employees: ["EMP001", "EMP002", "EMP003", "EMP004", "EMP005", "EMP006"]
    start_time: "09:00"
    end_time: "17:00"
    supervisor: "EMP002"
    
  evening_shift:
    employees: []
    start_time: "17:00" 
    end_time: "01:00"
    supervisor: null
    
  night_shift:
    employees: []
    start_time: "01:00"
    end_time: "09:00"
    supervisor: null