attendance_summary:
  this_month:
    average_attendance_rate: 93.2
    sick_leave_taken: 24
    total_overtime_hours: 156.25
    vacation_days_taken: 18
    working_days: 22
  this_week:
    average_attendance_rate: 94.5
    total_break_time_hours: 18.75
    total_days: 5
    total_overtime_hours: 42.5
  today:
    absent: 3
    average_hours_per_employee: 7.01
    early_departures: 2
    late_arrivals: 5
    present: 41
    total_hours_worked: 287.5
departments:
  Engineering:
    budget_code: ENG001
    location: Floor 3
    manager: John Smith
    name: Engineering
    off_duty: 1
    on_break: 2
    on_duty: 12
    on_leave: 0
    remote_work: 0
    total_staff: 15
  Finance:
    budget_code: FIN001
    location: Floor 1
    manager: Robert Taylor
    name: Finance
    off_duty: 1
    on_break: 0
    on_duty: 6
    on_leave: 1
    remote_work: 0
    total_staff: 8
  Human Resources:
    budget_code: HR001
    location: Floor 2
    manager: Sarah Johnson
    name: Human Resources
    off_duty: 1
    on_break: 1
    on_duty: 3
    on_leave: 0
    remote_work: 0
    total_staff: 5
  Marketing:
    budget_code: MKT001
    location: Floor 2
    manager: Emily Chen
    name: Marketing
    off_duty: 0
    on_break: 1
    on_duty: 5
    on_leave: 0
    remote_work: 0
    total_staff: 6
  Sales:
    budget_code: SAL001
    location: Floor 1
    manager: Mike Davis
    name: Sales
    off_duty: 0
    on_break: 1
    on_duty: 7
    on_leave: 0
    remote_work: 2
    total_staff: 10
employees:
  EMP001:
    attendance_score: 82.85144953584835
    break_start: null
    check_in_time: 09:15
    current_status: on_duty
    department: Engineering
    email: john.smith@company.com
    emergency_contact:
      name: Jane Smith
      phone: +1-555-0201
      relationship: Spouse
    employee_id: EMP001
    employee_type: full_time
    expected_check_out: '17:00'
    hire_date: '2023-01-15'
    last_status_update: '2025-10-12 14:30:00'
    location: Office Floor 3
    name: John Smith
    performance_rating: Satisfactory
    phone: +1-555-0101
    position: Senior Developer
    profile_image: null
    shift: morning
    total_hours_today: 5.25
  EMP002:
    attendance_score: 80.85884072563329
    break_start: '14:15'
    check_in_time: 08:45
    current_status: on_break
    department: Human Resources
    email: sarah.johnson@company.com
    emergency_contact:
      name: Mike Johnson
      phone: +1-555-0202
      relationship: Spouse
    employee_id: EMP002
    employee_type: full_time
    expected_check_out: '17:00'
    hire_date: '2022-03-20'
    last_status_update: '2025-10-12 14:15:00'
    location: Office Floor 2
    name: Sarah Johnson
    performance_rating: Satisfactory
    phone: +1-555-0102
    position: HR Manager
    profile_image: null
    shift: morning
    total_hours_today: 5.5
  EMP003:
    attendance_score: 82.59857764836858
    break_start: null
    check_in_time: 09:00
    current_status: remote_work
    department: Sales
    email: mike.davis@company.com
    emergency_contact:
      name: Lisa Davis
      phone: +1-555-0203
      relationship: Sister
    employee_id: EMP003
    employee_type: full_time
    expected_check_out: '17:00'
    hire_date: '2023-07-10'
    last_status_update: '2025-10-12 14:30:00'
    location: Remote - Home Office
    name: Mike Davis
    performance_rating: Satisfactory
    phone: +1-555-0103
    position: Sales Representative
    profile_image: null
    shift: morning
    total_hours_today: 5.5
  EMP004:
    attendance_score: 88.17032719786603
    break_start: null
    check_in_time: null
    current_status: on_leave
    department: Finance
    email: lisa.wilson@company.com
    emergency_contact:
      name: Tom Wilson
      phone: +1-555-0204
      relationship: Father
    employee_id: EMP004
    employee_type: full_time
    expected_check_out: null
    hire_date: '2022-11-05'
    last_status_update: '2025-10-11 17:00:00'
    location: Office Floor 1
    name: Lisa Wilson
    performance_rating: Good
    phone: +1-555-0104
    position: Financial Analyst
    profile_image: null
    shift: morning
    total_hours_today: 0
  EMP005:
    attendance_score: 83.54832876453604
    break_start: null
    check_in_time: 09:30
    current_status: on_duty
    department: Engineering
    email: david.brown@company.com
    emergency_contact:
      name: Mary Brown
      phone: +1-555-0205
      relationship: Mother
    employee_id: EMP005
    employee_type: full_time
    expected_check_out: '17:30'
    hire_date: '2024-02-01'
    last_status_update: '2025-10-12 09:30:00'
    location: Office Floor 3
    name: David Brown
    performance_rating: Satisfactory
    phone: +1-555-0105
    position: Junior Developer
    profile_image: null
    shift: morning
    total_hours_today: 5.0
  EMP006:
    attendance_score: 81.00309750078407
    break_start: null
    check_in_time: 08:45
    current_status: on_duty
    department: Marketing
    email: emily.chen@company.com
    emergency_contact:
      name: James Chen
      phone: +1-555-0206
      relationship: Spouse
    employee_id: EMP006
    employee_type: full_time
    expected_check_out: '16:45'
    hire_date: '2023-05-15'
    last_status_update: '2025-10-12 08:45:00'
    location: Office Floor 2
    name: Emily Chen
    performance_rating: Satisfactory
    phone: +1-555-0106
    position: Marketing Specialist
    profile_image: null
    shift: morning
    total_hours_today: 5.75
real_time_stats:
  currently_on_duty: 33
  last_updated: '2025-10-12 14:30:00'
  off_duty: 3
  on_break: 5
  on_leave: 1
  remote_workers: 2
  total_employees: 44
shift_assignments:
  evening_shift:
    employees: []
    end_time: 01:00
    start_time: '17:00'
    supervisor: null
  morning_shift:
    employees:
    - EMP001
    - EMP002
    - EMP003
    - EMP004
    - EMP005
    - EMP006
    end_time: '17:00'
    start_time: 09:00
    supervisor: EMP002
  night_shift:
    employees: []
    end_time: 09:00
    start_time: 01:00
    supervisor: null
